[project]
name = "hot-reload"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "gracjan.zukowski@enbio.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
hot-reload = "hot_reload:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
